spring.application.name=smart-banking

# Oracle Database
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=BANKING
spring.datasource.password=banking123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Server
server.port=8080

jwt.secret=smartbanking-jwt-secret-key-2026-09-abcdefghijklmnopqrstuvwxyz

